name: Run Python App with Secrets

on:
  push:
    branches:
      - main

env:
  TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  LANGSMITH_API_KEY: ${{ secrets.LANGSMITH_API_KEY }}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Python script with environment variables
        env:
          TMDB_API_KEY: ${{ env.TMDB_API_KEY }}
          OPENAI_API_KEY: ${{ env.OPENAI_API_KEY }}
          LANGSMITH_API_KEY: ${{ env.LANGSMITH_API_KEY }}
        run: python main.py
